import { Inter } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/component/AppNavbar";
import { AppProvider } from "@/component/UseContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fist Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <AppProvider>
        <AppNavbar/>
        {children}
        </AppProvider>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
      </body> 
    </html>
  );
}